name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.88.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup update --no-self-update stable
          rustup install ${{ env.RUST_VERSION }} --profile minimal
          rustup component add --toolchain ${{ env.RUST_VERSION }} rustfmt clippy
          rustup default ${{ env.RUST_VERSION }}

      - name: Run Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ env.RUST_VERSION }}"
          cache-all-crates: "true"

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Linting
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --no-clean --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          slug: amantoux/quill-delta-rs
          files: lcov.info
          fail_ci_if_error: true
